version: 1.2.{build}.{branch}
image: Visual Studio 2017
before_build:
  - echo ***** Appveyor.VS2017.yml ******
  - cmd: nuget restore TestAutomationEssentials.VS2017.sln -verbosity detailed
  
build:
  project: TestAutomationEssentials.VS2017.sln
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: drJnVViVjSHQzV1msgNjZb6SEYakcRMi5ssqyXi/a2Aawtwn+V8kgOXEerpa9aVm
  on:
    branch: master
notifications:
- provider: Email
  to:
  - arnona@sela.co.il
  subject: Build of TestAutomationEssentials completed succesfully
  on_build_success: true
  on_build_failure: false
  on_build_status_changed: false
- provider: Email
  to:
  - arnona@sela.co.il
  subject: Build of TestAutomationEssentials failed
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false
on_success:
  - cmd: nuget push TestAutomationEssentials.Common\bin\Debug\TestAutomationEssentials.Common.1.0.0.nupkg -ApiKey b1t018ptj25aqy2t3ypg5b95 -Source https://ci.appveyor.com/nuget/arnonax-i3v3ma77kcln/api/v2/package
  - cmd: powershell -file InvokeNextBuild.ps1